name: VDrift

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies and setup
      run: make dev

    - name: build
      run: make

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vdrift.app
        path: build/vdrift.app
